#变更后需要/npbook reload或重启MC服务器生效

# 发放模式:
#   new    - 仅新玩家发放
#   all    - 所有玩家每次登录发放
#   update - 如果进服玩家背包没有当前版本的书则发放(匹配条件 book:title)
give-mode: "update"
language: zh_CN  # 可选项: zh_CN, en_US 等
# 书本设置
book:
  # 书本显示名称（可选）
  name: "§6服务器指南"
  # 书本标题（用于give-mode: "update"模式识别书的版本,建议加上版本号或日期以区分不同发放版本）
  title: "欢迎指南v1.0"
  # 书本作者
  author: "服务器管理员"
  # 书本页面内容示例
  pages:
    - "欢迎来到我们的服务器！\n\n请阅读本指南了解基本规则和玩法。"
    - "<dark_red><bold>服务器规则:<reset>\n<red>1. <black>禁止作弊\n<red>2. <black>尊重其他玩家\n<red>3. <black>不要破坏他人建筑\n<red>4. <black>玩得开心~"
  # 书本附魔（格式: 附魔ID:等级）
  enchants:
    - "MENDING:1"